import {
  BookUser,
  Box,
  BoxesIcon,
  Briefcase,
  CalendarCheck,
  ClipboardEditIcon,
  Contact,
  Container,
  CreditCard,
  LucideBox,
  Mail,
  MessageSquare,
  MonitorDot,
  Package,
  PackageCheck,
  PackageCheckIcon,
  PackageMinus,
  PackageMinusIcon,
  PackagePlus,
  PictureInPicture2,
  PieChart,
  ReceiptText,
  ShoppingCart,
  Tag,
  Truck,
  User,
  UserMinus2,
  UserPlus2Icon,
  UserRound,
  UserRoundCheck,
  Warehouse,
} from "lucide-react";

const menuData: any = [
  {
    label: "menu",
    isTitle: true,
  },
  {
    id: "dashboard",
    label: "Dashboards",
    link: "/#",
    icon: <MonitorDot />,
  },
  {
    label: "Data Master",
    isTitle: true,
  },
  {
    id: "User",
    label: "User",
    icon: <User />,
    link: "/master-user",
    parentId: 1,
  },
  {
    id: "Category",
    label: "Kategori Barang",
    icon: <Tag />,
    link: "/kategori-barang",
    parentId: 2,
  },
  {
    id: "barang",
    label: "Barang",
    icon: <Box />,
    link: "/master-barang",
    parentId: 2,
  },
  {
    id: "pemasok",
    label: "Supplier",
    icon: <Truck />,
    link: "/supplier",
    parentId: 3,
  },
  {
    id: "customer",
    label: "Customer",
    icon: <Briefcase />,
    link: "/customer",
    parentId: 4,
  },
  {
    label: "Purchase & Sales",
    isTitle: true,
  },
  {
    id: "purchase",
    label: "Purchase",
    icon: <ShoppingCart />,
    link: "/purchase",
    parentId: 1,
  },
  {
    id: "sales",
    label: "Sales",
    icon: <ReceiptText />,
    link: "/sales",
    parentId: 2,
  },
  {
    label: "Employee",
    isTitle: true,
  },
  {
    id: "Employee",
    label: "Employee",
    icon: <BookUser />,
    link: "/employee",
    parentId: 1,
  },
  // {
  //   id: "Service",
  //   label: "Service",
  //   icon: <BookUser />,
  //   link: "/service",
  //   parentId: 1,
  // },
  {
    id: "Attendance",
    label: "Attendance",
    icon: <CalendarCheck />,
    link: "/attendance",
    parentId: 2,
  },
  {
    id: "Payroll",
    label: "Payroll",
    icon: <CreditCard />,
    link: "/payroll",
    parentId: 1,
  },


  {
    label: "Laporan",
    isTitle: true,
  },
  {
    id: "laporan_barang_tersedia",
    label: "Laporan Stok Barang Tersedia",
    icon: <PackagePlus />,
    link: "/report-barang-tersedia",
    parentId: 1,
  },
  {
    id: "laporan_barang_habis",
    label: "Laporan Stok Barang Habis",
    icon: <PackageMinus />,
    link: "/report-barang-habis",
    parentId: 1,
  },
  {
    id: "laporan_pembelian",
    label: "Laporan Pembelian",
    icon: <ReceiptText />,
    link: "/report-pembelian",
    parentId: 1,
  },
  {
    id: "laporan_penjualan",
    label: "Laporan Penjualan",
    icon: <ReceiptText />,
    link: "/report-penjualan",
    parentId: 1,
  },
  {
    id: "laporan_employee",
    label: "Laporan Karyawan",
    icon: <User />,
    link: "/report-employee",
    parentId: 1,
  },
  {
    id: "laporan_absensi",
    label: "Laporan Absensi",
    icon: <UserRoundCheck />,
    link: "/report-absensi",
    parentId: 1,
  },
  {
    id: "laporan_payroll",
    label: "Laporan Payroll",
    icon: <CreditCard />,
    link: "/report-payroll",
    parentId: 1,
  },
  {
    id: "laporan_stock_movements",
    label: "Laporan Stok Movements",
    icon: <PackageCheck />,
    link: "/report-stock-movements",
    parentId: 1,
  },

  // {
  //   id: "laporan_service",
  //   label: "Laporan Service",
  //   icon: <UserRoundCheck />,
  //   link: "/report-service",
  //   parentId: 1,
  // },

  // {
  //   id: "laporan_pelanggan",
  //   label: "Laporan Pelanggan",
  //   icon: <UserMinus2 />,
  //   link: "/report-pelanggan",
  //   parentId: 2,
  // },
  // {
  //   id: "mutasi_barang",
  //   label: "Laporan Mutasi Barang",
  //   icon: <PieChart />,
  //   link: "/report-mutasi",
  //   parentId: 3,
  // },
  // {
  //   id: "barang_tersedia",
  //   label: "Laporan Stok Barang Tersedia",
  //   icon: <BoxesIcon />,
  //   link: "/report-barang-tersedia",
  //   parentId: 4,
  // },
  // {
  //   id: "barang_habis",
  //   label: "Laporan Stok Barang Kosong",
  //   icon: <LucideBox />,
  //   link: "/report-barang-habis",
  //   parentId: 5,
  // },

];

export { menuData };
