import {
  BookUser,
  Box,
  BoxesIcon,
  Briefcase,
  CalendarCheck,
  ClipboardEditIcon,
  Contact,
  Container,
  CreditCard,
  LucideBox,
  Mail,
  MessageSquare,
  MonitorDot,
  Package,
  PackageCheckIcon,
  PackageMinusIcon,
  PictureInPicture2,
  PieChart,
  ReceiptText,
  ShoppingCart,
  Tag,
  Truck,
  User,
  UserMinus2,
  UserPlus2Icon,
  Warehouse,
} from "lucide-react";

const menuData: any = [
  {
    label: "menu",
    isTitle: true,
  },
  {
    id: "dashboard",
    label: "Dashboards",
    link: "/#",
    icon: <MonitorDot />,
  },
  {
    label: "Data Master",
    isTitle: true,
  },
  {
    id: "User",
    label: "User",
    icon: <User />,
    link: "/master-user",
    parentId: 1,
  },
  {
    id: "Category",
    label: "Kategori Barang",
    icon: <Tag />,
    link: "/kategori-barang",
    parentId: 2,
  },
  {
    id: "barang",
    label: "Barang",
    icon: <Box />,
    link: "/master-barang",
    parentId: 2,
  },
  {
    id: "pemasok",
    label: "Supplier",
    icon: <Truck />,
    link: "/supplier",
    parentId: 3,
  },
  {
    id: "customer",
    label: "Customer",
    icon: <Briefcase />,
    link: "/customer",
    parentId: 4,
  },
  {
    label: "Purchase & Sales",
    isTitle: true,
  },
  {
    id: "purchase",
    label: "Purchase",
    icon: <ShoppingCart />,
    link: "/purchase",
    parentId: 1,
  },
  {
    id: "sales",
    label: "Sales",
    icon: <ReceiptText />,
    link: "/sales",
    parentId: 2,
  },
  {
    label: "Employee",
    isTitle: true,
  },
  {
    id: "Employee",
    label: "Employee",
    icon: <BookUser />,
    link: "/employee",
    parentId: 1,
  },
  {
    id: "Attendance",
    label: "Attendance",
    icon: <CalendarCheck />,
    link: "/attendance",
    parentId: 2,
  },
  {
    label: "Payroll",
    isTitle: true,
  },
  {
    id: "Payroll",
    label: "Payroll",
    icon: <CreditCard />,
    link: "/payroll",
    parentId: 1,
  },
  // {
  //   label: "Laporan",
  //   isTitle: true,
  // },
  // {
  //   id: "laporan_pemasok",
  //   label: "Laporan Pemasok",
  //   icon: <UserPlus2Icon />,
  //   link: "/report-pemasok",
  //   parentId: 1,
  // },
  // {
  //   id: "laporan_pelanggan",
  //   label: "Laporan Pelanggan",
  //   icon: <UserMinus2 />,
  //   link: "/report-pelanggan",
  //   parentId: 2,
  // },
  // {
  //   id: "mutasi_barang",
  //   label: "Laporan Mutasi Barang",
  //   icon: <PieChart />,
  //   link: "/report-mutasi",
  //   parentId: 3,
  // },
  // {
  //   id: "barang_tersedia",
  //   label: "Laporan Stok Barang Tersedia",
  //   icon: <BoxesIcon />,
  //   link: "/report-barang-tersedia",
  //   parentId: 4,
  // },
  // {
  //   id: "barang_habis",
  //   label: "Laporan Stok Barang Kosong",
  //   icon: <LucideBox />,
  //   link: "/report-barang-habis",
  //   parentId: 5,
  // },

];

export { menuData };
